import  { Roboto } from 'next/font/google'
import * as Link  from 'next/link'
import "./second.css"

const roboto = Roboto({ subsets: ["cyrillic"], weight: "400" })

export const metadata = {
  title: 'TATA_BAGS_Learn',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="wrapper">
          <div className="menu-header">
            <Link href={"/"}>HOME</Link>
            <br />
            <Link href={"/second"}>SECOND</Link>
            <br />
            <Link href={"/blogg/slugpage"}>slugpage</Link>
            <br />
          </div>
        {children}
        </div>
        </body>
    </html>
  )
}
