import  { Roboto } from 'next/font/google'

const roboto = Roboto({ subsets: ["cyrillic"], weight: "400" })

export const metadata = {
  title: 'TATA_BAGS_Learn',
  description: 'Generated by create next app',
}
const pros = "VALID OR NOOOOT"

export default async function RootLayout({ children }) {
  const DATA_SY = await DataJson()
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
        </body>
    </html>
  )
}
